-- Seed catalogue. Stands in for the RCDB integration that is out of scope for v1:
-- 54 real coasters spread across 11 countries, 12 manufacturers and 3 types so the
-- dashboard stats and the leaderboard are meaningful in a demo.
-- Idempotent: re-running will not duplicate rows (see coasters_name_park_uniq).

insert into public.coasters (name, park, country, manufacturer, type) values
  ('Nemesis',                'Alton Towers',                 'United Kingdom', 'Bolliger & Mabillard',         'Steel'),
  ('Oblivion',               'Alton Towers',                 'United Kingdom', 'Bolliger & Mabillard',         'Steel'),
  ('The Smiler',             'Alton Towers',                 'United Kingdom', 'Gerstlauer',                   'Steel'),
  ('Wicker Man',             'Alton Towers',                 'United Kingdom', 'Great Coasters International', 'Wooden'),
  ('Stealth',                'Thorpe Park',                  'United Kingdom', 'Intamin',                      'Steel'),
  ('The Swarm',              'Thorpe Park',                  'United Kingdom', 'Bolliger & Mabillard',         'Steel'),
  ('Nemesis Inferno',        'Thorpe Park',                  'United Kingdom', 'Intamin',                      'Steel'),
  ('Icon',                   'Blackpool Pleasure Beach',     'United Kingdom', 'Mack Rides',                   'Steel'),
  ('The Big One',            'Blackpool Pleasure Beach',     'United Kingdom', 'Arrow Dynamics',               'Steel'),
  ('Infusion',               'Blackpool Pleasure Beach',     'United Kingdom', 'Vekoma',                       'Steel'),
  ('Millennium Force',       'Cedar Point',                  'United States',  'Intamin',                      'Steel'),
  ('Steel Vengeance',        'Cedar Point',                  'United States',  'Rocky Mountain Construction',  'Hybrid'),
  ('Maverick',               'Cedar Point',                  'United States',  'Intamin',                      'Steel'),
  ('Top Thrill 2',           'Cedar Point',                  'United States',  'Zamperla',                     'Steel'),
  ('Fury 325',               'Carowinds',                    'United States',  'Bolliger & Mabillard',         'Steel'),
  ('El Toro',                'Six Flags Great Adventure',    'United States',  'Intamin',                      'Wooden'),
  ('Nitro',                  'Six Flags Great Adventure',    'United States',  'Bolliger & Mabillard',         'Steel'),
  ('Kingda Ka',              'Six Flags Great Adventure',    'United States',  'Intamin',                      'Steel'),
  ('The Voyage',             'Holiday World',                'United States',  'The Gravity Group',            'Wooden'),
  ('Iron Gwazi',             'Busch Gardens Tampa Bay',      'United States',  'Rocky Mountain Construction',  'Hybrid'),
  ('SheiKra',                'Busch Gardens Tampa Bay',      'United States',  'Bolliger & Mabillard',         'Steel'),
  ('Montu',                  'Busch Gardens Tampa Bay',      'United States',  'Bolliger & Mabillard',         'Steel'),
  ('VelociCoaster',          'Islands of Adventure',         'United States',  'Intamin',                      'Steel'),
  ('Hagrid''s Magical Creatures Motorbike Adventure',
                             'Islands of Adventure',         'United States',  'Intamin',                      'Steel'),
  ('X2',                     'Six Flags Magic Mountain',     'United States',  'Arrow Dynamics',               'Steel'),
  ('Twisted Colossus',       'Six Flags Magic Mountain',     'United States',  'Rocky Mountain Construction',  'Hybrid'),
  ('Taron',                  'Phantasialand',                'Germany',        'Intamin',                      'Steel'),
  ('F.L.Y.',                 'Phantasialand',                'Germany',        'Vekoma',                       'Steel'),
  ('Blue Fire',              'Europa-Park',                  'Germany',        'Mack Rides',                   'Steel'),
  ('Silver Star',            'Europa-Park',                  'Germany',        'Bolliger & Mabillard',         'Steel'),
  ('Voltron Nevera',         'Europa-Park',                  'Germany',        'Mack Rides',                   'Steel'),
  ('Wodan Timbur Coaster',   'Europa-Park',                  'Germany',        'Great Coasters International', 'Wooden'),
  ('Schwur des Kaernan',     'Hansa-Park',                   'Germany',        'Gerstlauer',                   'Steel'),
  ('Expedition GeForce',     'Holiday Park',                 'Germany',        'Intamin',                      'Steel'),
  ('Untamed',                'Walibi Holland',               'Netherlands',    'Rocky Mountain Construction',  'Hybrid'),
  ('Baron 1898',             'Efteling',                     'Netherlands',    'Bolliger & Mabillard',         'Steel'),
  ('Python',                 'Efteling',                     'Netherlands',    'Vekoma',                       'Steel'),
  ('Joris en de Draak',      'Efteling',                     'Netherlands',    'Great Coasters International', 'Wooden'),
  ('Zadra',                  'Energylandia',                 'Poland',         'Rocky Mountain Construction',  'Hybrid'),
  ('Hyperion',               'Energylandia',                 'Poland',         'Intamin',                      'Steel'),
  ('Shambhala',              'PortAventura Park',            'Spain',          'Bolliger & Mabillard',         'Steel'),
  ('Red Force',              'Ferrari Land',                 'Spain',          'Intamin',                      'Steel'),
  ('Steel Dragon 2000',      'Nagashima Spa Land',           'Japan',          'D. H. Morgan Manufacturing',   'Steel'),
  ('Hakugei',                'Nagashima Spa Land',           'Japan',          'Rocky Mountain Construction',  'Hybrid'),
  ('Eejanaika',              'Fuji-Q Highland',              'Japan',          'S&S Worldwide',                'Steel'),
  ('Do-Dodonpa',             'Fuji-Q Highland',              'Japan',          'S&S Worldwide',                'Steel'),
  ('Foenix',                 'Faarup Sommerland',            'Denmark',        'Vekoma',                       'Steel'),
  ('Piraten',                'Djurs Sommerland',             'Denmark',        'Intamin',                      'Steel'),
  ('Helix',                  'Liseberg',                     'Sweden',         'Mack Rides',                   'Steel'),
  ('Balder',                 'Liseberg',                     'Sweden',         'Intamin',                      'Wooden'),
  ('Leviathan',              'Canada''s Wonderland',         'Canada',         'Bolliger & Mabillard',         'Steel'),
  ('Yukon Striker',          'Canada''s Wonderland',         'Canada',         'Bolliger & Mabillard',         'Steel'),
  ('DC Rivals HyperCoaster', 'Warner Bros. Movie World',     'Australia',      'Mack Rides',                   'Steel'),
  ('Steel Taipan',           'Dreamworld',                   'Australia',      'Mack Rides',                   'Steel')
on conflict do nothing;
